/**
 * [LAYER: INFRASTRUCTURE]
 * Principle: Structural Observability — generates the live JOY_MAP.md metrics dashboard.
 * Pass 11: Metric-Driven Architectural Health.
 */

import { SqliteJoyCacheRepository } from '../database/SqliteJoyCacheRepository';
import { SqliteHealingRepository } from '../database/SqliteHealingRepository';
import { SovereignDb } from '../database/SovereignDb';
import * as fs from 'fs';
import * as path from 'path';

export class JoyMapGenerator {
    private joyCache: SqliteJoyCacheRepository;
    private healingRepo: SqliteHealingRepository;

    constructor() {
        this.joyCache = new SqliteJoyCacheRepository();
        this.healingRepo = new SqliteHealingRepository();
    }

    /**
     * Aggregates metrics and generates the JOY_MAP.md dashboard.
     */
    async generate(projectRoot: string): Promise<void> {
        console.log('🗺️  [JoyMap] Aggregating architectural metrics...');
        
        // 1. Get Top 5 Architectural Anchors
        const anchors = await this.joyCache.getTopArchitecturalAnchors(5);
        
        // 2. Get Open Remediation Proposals
        const recentProposals = await this.healingRepo.listRecentProposals(5);

        // 3. Build Dashboard Markdown
        let md = `# 🗺️ JoyMap: Architectural Health Dashboard\n\n`;
        md += `> [!NOTE]\n`;
        md += `> This dashboard is a live reflection of the Sovereign Guard's architectural analysis.\n\n`;

        md += `## 🏗️ Architectural Anchors\n`;
        md += `The most critical implementation bottlenecks in the project (Highest Afferent Coupling).\n\n`;
        md += `| File Path | Inbound Dependencies (Ca) | Impact |\n`;
        md += `| :--- | :--- | :--- |\n`;
        
        for (const anchor of anchors) {
            const relPath = path.relative(projectRoot, anchor.path);
            const impact = anchor.count > 10 ? '🔴 HIGH (God File)' : anchor.count > 5 ? '🟡 MEDIUM' : '🟢 STABLE';
            md += `| \`${relPath}\` | **${anchor.count}** | ${impact} |\n`;
        }

        md += `\n## 🩹 Active Remediation Proposals\n`;
        if (recentProposals.length > 0) {
            md += `Latest architectural improvement plans generated by the HealingService.\n\n`;
            for (const p of recentProposals) {
                const icon = p.violationId === 'PROACTIVE_COUPLING' ? '💡' : '🛡️';
                md += `- **${icon} [${p.status}]** ${p.rationale}\n`;
            }
        } else {
            md += `✨ No outstanding architectural violations detected.\n`;
        }

        md += `\n## ⚖️ Layer Stability Model\n`;
        md += `| Layer | Core Principle | Rule |\n`;
        md += `| :--- | :--- | :--- |\n`;
        md += `| **DOMAIN** | Business Logic | No external imports |\n`;
        md += `| **CORE** | Orchestration | Only DOMAIN imports |\n`;
        md += `| **INFRA** | Implementation | DOMAIN + CORE only |\n`;
        md += `| **UI** | Delivery | All layers |\n`;

        md += `\n\n---
Generated by **JoyZoning sovereign-guard-v1** on ${new Date().toLocaleString()}
`;

        const outputPath = path.join(projectRoot, 'JOY_MAP.md');
        fs.writeFileSync(outputPath, md);
        
        console.log(`✨ [JoyMap] Dashboard updated: ${outputPath}`);
    }
}
