/**
 * Copyright (c) 2026 DietCode Contributors
 * 
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
/**
 * [LAYER: INFRASTRUCTURE]
 * Principle: Structural Observability — generates the live JOY_MAP.md metrics dashboard.
 * Pass 11: Metric-Driven Architectural Health.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { SqliteHealingRepository } from '../database/SqliteHealingRepository';
import { SqliteJoyCacheRepository } from '../database/SqliteJoyCacheRepository';
import { Core } from '../database/sovereign/Core';

export class JoyMapGenerator {
  private joyCache: SqliteJoyCacheRepository;
  private healingRepo: SqliteHealingRepository;
  private projectRoot = '';

  constructor() {
    this.joyCache = new SqliteJoyCacheRepository();
    this.healingRepo = new SqliteHealingRepository();
  }

  /**
   * Aggregates metrics and generates the JOY_MAP.md dashboard.
   */
  async generate(projectRoot: string): Promise<void> {
    this.projectRoot = projectRoot;
    console.log('🗺️  [JoyMap] Aggregating architectural metrics...');

    // 1. Get Top 5 Architectural Anchors
    const anchors = await this.joyCache.getTopArchitecturalAnchors(5);

    // 2. Get Open Remediation Proposals
    const recentProposals = await this.healingRepo.listRecentProposals(5);

    // 3. Generate Mermaid Dependency Oracle
    const mermaid = await this.generateMermaidOracle();

    // 4. Generate Health Evolution Trend
    const trend = await this.generateHealthTrend();

    // 5. Generate Orphaned Files (Dead Code)
    const orphans = await this.joyCache.getProjectOrphans(this.projectRoot);

    // 6. Build Dashboard Markdown
    let md = '# 🔮 JoyMap: Divine Architectural Forge\n\n';
    md += '> [!NOTE]\n';
    md += `> This dashboard is a live reflection of the Sovereign Guard's architectural analysis.\n\n`;

    md += '## 📈 Structural Health History\n';
    md += `Evolutionary trend of the project's architectural integrity.\n\n`;
    md += `${trend}\n\n`;

    md += '## 🌑 Orphaned Files (Dead Code)\n';
    md += 'Files with zero inbound dependencies that may be safe to prune.\n\n';
    if (orphans.length > 0) {
      for (const o of orphans) {
        md += `- \`${o}\`\n`;
      }
    } else {
      md += '_No orphans detected. Codebase is lean and purposeful._\n';
    }
    md += '\n';

    md += '## 🔮 Dependency Oracle\n';
    md += `Mermaid-driven visualization of the project's **actual** architectural flow.\n\n`;
    md += `\`\`\`mermaid\n${mermaid}\n\`\`\`\n\n`;

    md += '## 🏗️ Architectural Anchors\n';
    md +=
      'The most critical implementation bottlenecks in the project (Highest Afferent Coupling).\n\n';
    md += '| File Path | Inbound Dependencies (Ca) | Impact |\n';
    md += '| :--- | :--- | :--- |\n';

    for (const anchor of anchors) {
      const relPath = path.relative(projectRoot, anchor.path);
      const impact =
        anchor.count > 10 ? '🔴 HIGH (God File)' : anchor.count > 5 ? '🟡 MEDIUM' : '🟢 STABLE';
      md += `| \`${relPath}\` | **${anchor.count}** | ${impact} |\n`;
    }

    md += '\n## 🩹 Active Remediation Proposals\n';
    if (recentProposals.length > 0) {
      md += 'Latest architectural improvement plans generated by the HealingService.\n\n';
      for (const p of recentProposals) {
        const icon = p.violationId === 'PROACTIVE_COUPLING' ? '💡' : '🛡️';
        md += `- **${icon} [${p.status}]** ${p.rationale}\n`;
      }
    } else {
      md += '✨ No outstanding architectural violations detected.\n';
    }

    md += '\n## ⚖️ Layer Stability Model\n';
    md += '| Layer | Core Principle | Allowed Imports |\n';
    md += '| :--- | :--- | :--- |\n';
    md += '| **DOMAIN** | Business Logic | (None) |\n';
    md += '| **CORE** | Orchestration | Domain, Infrastructure, Plumbing |\n';
    md += '| **INFRA** | Implementation | Domain, Plumbing |\n';
    md += '| **UI** | Delivery | Domain, Plumbing (**No Infra**) |\n';
    md += '| **PLUMBING** | Utils/Cross-cutting | (None) |\n';

    md += `\n\n---
Generated by **JoyZoning sovereign-guard-v1** on ${new Date().toLocaleString()}
`;

    const outputPath = path.join(projectRoot, 'JOY_MAP.md');
    fs.writeFileSync(outputPath, md);

    console.log(`✨ [JoyMap] Dashboard updated: ${outputPath}`);
  }

  private async generateHealthTrend(): Promise<string> {
    const db = await Core.db();
    const history = await (db as any)
      .selectFrom('joy_history' as any)
      .selectAll()
      .orderBy('timestamp', 'desc')
      .limit(10)
      .execute();

    if (history.length === 0) return '_Architectural history recording initiated..._';

    let md = '| Date | Score | Violations | File Count | Delta |\n';
    md += '| :--- | :--- | :--- | :--- | :--- |\n';

    for (let i = 0; i < history.length; i++) {
      const h = history[i] as any;
      const prev = history[i + 1] as any;
      let delta = '⏺️';

      if (prev) {
        const diff = h.score - prev.score;
        if (diff > 0) delta = `📈 +${diff}`;
        else if (diff < 0) delta = `📉 ${diff}`;
      }

      const dateStr = new Date(h.timestamp).toLocaleString();
      md += `| ${dateStr} | **${h.score}** | ${h.violation_count} | ${h.file_count} | ${delta} |\n`;
    }

    return md;
  }

  private async generateMermaidOracle(): Promise<string> {
    const db = await Core.db();
    const results = await (db as any)
      .selectFrom('joy_imports' as any)
      .select(['source_path', 'imported_path'])
      .execute();

    const connections = new Map<string, number>();

    for (const row of results as any[]) {
      const sourceLayer = this.getLayerFromPath(row.source_path);
      const targetLayer = this.getLayerFromPath(row.imported_path);

      if (sourceLayer !== targetLayer && sourceLayer !== 'UNKNOWN' && targetLayer !== 'UNKNOWN') {
        const key = `${sourceLayer} --> ${targetLayer}`;
        connections.set(key, (connections.get(key) || 0) + 1);
      }
    }

    let mermaid = 'graph TD\n';
    for (const [conn, count] of connections) {
      mermaid += `  ${conn.split(' --> ')[0]} --(${count})--> ${conn.split(' --> ')[1]}\n`;
    }

    // Add Styles
    mermaid += '  style DOMAIN fill:#e1f5fe,stroke:#01579b\n';
    mermaid += '  style CORE fill:#fff3e0,stroke:#e65100\n';
    mermaid += '  style INFRASTRUCTURE fill:#f3e5f5,stroke:#4a148c\n';
    mermaid += '  style PLUMBING fill:#e8f5e9,stroke:#1b5e20\n';

    return mermaid;
  }

  private getLayerFromPath(pathName: string): string {
    if (pathName.includes('src/domain')) return 'DOMAIN';
    if (pathName.includes('src/core')) return 'CORE';
    if (pathName.includes('src/infrastructure')) return 'INFRASTRUCTURE';
    if (pathName.includes('src/ui')) return 'UI';
    if (pathName.includes('src/plumbing') || pathName.includes('src/utils')) return 'PLUMBING';
    return 'UNKNOWN';
  }
}
